#!/bin/bash

AWS_PROFILE=default
ROLE_NAME=sam-test-ecs-role

aws --profile $AWS_PROFILE iam create-role \
  --role-name $ROLE_NAME \
  --assume-role-policy-document file://aws/container-service-task-role.json
